#!/bin/bash 


cd ~/Dropbox/wiki/
/usr/bin/find . -name "*.md" | while read i; do 
    file_name="${i##*/}"; md_dir="${i%${file_name}}";html_dir="${md_dir//md/html}";
    if [ ! -d "$html_dir" ]
    then 
        echo "${html_dir} does not exist";
        mkdir $html_dir
    fi
    /usr/bin/pandoc -s -c ~/.pandoc/epub.css "${i}" -o "${html_dir}${file_name//md/html}"
done
